### ISSUE TITLE
Invalid String format error on start

### ISSUE THREAD

**Issue by AWL-Gaming** [Salvatore-Als/palworld-discord-players#1]
Bot doesn't start even tho the .env file is fully populated:

`DISCORD_TOKEN = "REDACTED.TOKEN.TOEKN"
BOT_PREFIX = "++"
SERVER_IP = "ip_added"
RCON_PORT = "25575"
RCON_PASSWORD = "server_pw"
COMMAND_NAME = "YOUR_COMMAND_NAME"`
![image](https://github.com/Salvatore-Als/palworld-discord-players/assets/22678541/75ce99ed-9515-4447-816e-40351e8c73a5)

**Comment by Salvatore-Als** [comment]
Because of the prefix, Discord not allowed "++" on the player name.
Please try with "Palworld " or something like this :)

**Comment by AWL-Gaming** [comment]
> Because of the prefix, Discord not allowed "++" on the player name. Please try with "Palworld " or something like this :)

This worked thank you

**Comment by Salvatore-Als** [comment]
Nice, np :D
